export const backgroundImages = [
    '/xp/welcome-long.png',
    '/xp/windows-xp-wallpaper-bliss.png'
]

export const assets = {
    "alert": "/xp/alert.png",
    "back": "/xp/back.png",
    "btn1": "/xp/btn1.png",
    "btn2": "/xp/btn2.png",
    "btn3": "/xp/btn3.png",
    "calculator": "/xp/calculator.png",
    "chrome": "/xp/chrome.png",
    "cmd": "/xp/cmd.png",
    "computer": "/xp/computer.png",
    "documents": "/xp/documents.png",
    "drivers": "/xp/drivers.png",
    "email": "/xp/email.png",
    "file": "/xp/file.png",
    "folder": "/xp/folder.png",
    "github": "/xp/github-logo.png",
    "help": "/xp/help.png",
    "home": "/xp/home.png",
    "ie": "/xp/ie.png",
    "linkedin": "/xp/linkedin.png",
    "logoff": "/xp/logoff.png",
    "messenger": "/xp/messenger.png",
    "msn": "/xp/msn.png",
    "musics": "/xp/musics.png",
    "network": "/xp/network.png",
    "notepad": "/xp/notepad.png",
    "pictures": "/xp/pictures.png",
    "recycle": "/xp/recycle.png",
    "run": "/xp/run.png",
    "search": "/xp/search.png",
    "sound": "/xp/sound.png",
    "turnoff": "/xp/turnoff.png",
    "user": "/xp/user.png",
    "winPlayer": "/xp/winPlayer.png"
}